### PR TITLE
Switch to voxpupuli-rubocop

### PR DESCRIPTION
**Pull request by bastelfreak**
## Summary
Provide a detailed description of all the changes present in this pull request.

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
- [ ] Thought process behind the implementation.

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified.

### CODE REVIEW

**Comment by david22swan** [comment]
@bastelfreak If you could you resolve the conflicts we've planned to merge this

**Comment by david22swan** [comment]
@bastelfreak This still something you want merged?

**Comment by bastelfreak** [comment]
oh sorry I missed your last comment. let me rebase.

**Comment by bastelfreak** [comment]
I'm not yet sure what's broken here, but someone just reported the same issue in the ra10ke project:

```
bundle exec rake -T                                                                                                                                       1 ↵
rake aborted!
ArgumentError: wrong number of arguments (given 1, expected 0)
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/json_pure-2.7.2/lib/json/common.rb:86:in `initialize'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/json_pure-2.7.2/lib/json/common.rb:86:in `new'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/json_pure-2.7.2/lib/json/common.rb:86:in `create_fast_state'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/json_pure-2.7.2/lib/json/common.rb:79:in `generator='
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/json_pure-2.7.2/lib/json/ext.rb:11:in `<module:Ext>'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/json_pure-2.7.2/lib/json/ext.rb:6:in `<module:JSON>'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/json_pure-2.7.2/lib/json/ext.rb:3:in `<top (required)>'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/json_pure-2.7.2/lib/json.rb:588:in `require'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/json_pure-2.7.2/lib/json.rb:588:in `<module:JSON>'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/json_pure-2.7.2/lib/json.rb:584:in `<top (required)>'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/solve-4.0.4/lib/solve/solver/serializer.rb:1:in `require'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/solve-4.0.4/lib/solve/solver/serializer.rb:1:in `<top (required)>'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/solve-4.0.4/lib/solve/ruby_solver.rb:4:in `require_relative'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/solve-4.0.4/lib/solve/ruby_solver.rb:4:in `<top (required)>'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/solve-4.0.4/lib/solve.rb:10:in `require_relative'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/solve-4.0.4/lib/solve.rb:10:in `<module:Solve>'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/solve-4.0.4/lib/solve.rb:3:in `<top (required)>'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/ra10ke-2.0.0/lib/ra10ke/solve.rb:6:in `require'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/ra10ke-2.0.0/lib/ra10ke/solve.rb:6:in `<top (required)>'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/ra10ke-2.0.0/lib/ra10ke.rb:4:in `require'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/ra10ke-2.0.0/lib/ra10ke.rb:4:in `<top (required)>'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/Rakefile:6:in `require'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/Rakefile:6:in `<top (required)>'
/Users/zipkid/source/vrt/puppet/vagrant-puppet/puppet_r10k/vendor/ruby/2.7.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/Users/zipkid/.rbenv/versions/2.7.7/bin/bundle:23:in `load'
/Users/zipkid/.rbenv/versions/2.7.7/bin/bundle:23:in `<main>'
```

**Comment by bastelfreak** [comment]
Ah you reported it in https://github.com/ruby/json/issues/646

**Comment by bastelfreak** [comment]
@david22swan can you take another look?

**Review by david22swan — APPROVED** [review]

**Pull request merged**
