### PR TITLE
Handle nil autorequire results

### PR DESCRIPTION
**Pull request by seanmil**
When encountering results containing nil from an autorequire-family
call, Puppet will skip over them without error but rspec-puppet
results in an error. This aligns rspec-puppet with Puppet's
behavior.

Also, rename the autorelationships spec test so that it runs
properly as part of a 'rake spec' invocation.

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Looks like it was my bad when I wrote this in a PR.

**Comment by seanmil** [comment]
> Looks like it was my bad when I wrote this in a PR.

I just pushed an update I expect will fix the test failures on Windows. Thanks!

**Review by ekohl — APPROVED** [review]
Thanks! While I don't have access on this repo, it looks good to me.

**Review by michaeltlombardi — APPROVED** [review]
Thanks for the improvement to the code and the tests both! LGTM!

**Pull request merged**
